import { PROJECT_NAME } from "./config";

export enum LocalStorageEnum {
  LANGUAGE = PROJECT_NAME + "_LANGUAGE",
  TOKEN_KEY = PROJECT_NAME + "_TOKEN_KEY",
  CART_KEY = PROJECT_NAME + "_CART_KEY",
  FCM_TOKEN_KEY = PROJECT_NAME + "_FCM_TOKEN_KEY",


  USER_KEY = PROJECT_NAME + "_USER_KEY",
  GUEST_KEY = PROJECT_NAME + "_GUEST_KEY",
}
